---

- name: Clone fzy
  git:
    repo: https://github.com/jhawthorn/fzy.git
    dest: "{{ third_party_src }}/fzy"
  when: ansible_facts["os_family"] == "RedHat"

- name: Compile and install fzy
  shell: make && make install
  become: yes
  args:
    chdir: "{{ third_party_src }}/fzy"
    creates: /usr/local/bin/fzy
  when: ansible_facts["os_family"] == "RedHat"

- name: Install fzy
  become: true
  apt:
    name: fzy
    state: present
  when: ansible_facts["distribution"] == "Ubuntu"
